name: build check windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
  
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          mkdir lib
          cd lib
          pwd
          dir
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          # git clone https://github.com/razterizer/8Beat.git
          # git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules

      # Step 3: Change to the correct directory and build
      - name: Run build.bat
        continue-on-error: false # Ensure errors are not bypassed
        run: |
          cd $env:GITHUB_WORKSPACE\TextUR
          ./build.bat

